# Remove '#' to select a file or turn off linting.

# Linting with BLACK (Python) enhances code suggestions from LLMs. To disable linting, uncomment the relevant option in the linting settings.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[linting]
# "linting" = "off"

[files]
# Dockerfile = "selected"
"app.py" = "selected"
"app/__init__.py" = "selected"
"app/app.py" = "selected"
"app/auth.py" = "selected"
"app/continuous_gantt.py" = "selected"
# "app/ics.py" = "selected"
"app/jira_api.py" = "selected"
# "app/routes.py" = "selected"
"app/static/styles.css" = "selected"
# "app/static/template.xlsx" = "selected"
"app/templates/index.html" = "selected"
"app/templates/login.html" = "selected"
# "app/wsgi.py" = "selected"
# "index.html" = "selected"
# "jira_api.py" = "selected"
# "requirements.txt" = "selected"
# "routes.py" = "selected"
# "tests/test_app.py" = "selected"
"wsgi.py" = "selected"
# 