# Remove '#' to select a file or turn off linting.

# Linting with BLACK (Python) enhances code suggestions from LLMs. To disable linting, uncomment the relevant option in the linting settings.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[linting]
# "linting" = "off"

[files]
"app.py" = "selected"
"app/app.py" = "selected"
"app/continuous_gantt.py" = "selected"
# "requirements.txt" = "selected"
"routes.py" = "selected"
"templates/index.html" = "selected"
# 